/*
The MIT License (MIT)

Copyright (c) 2016 Saiid Al-Halawi
*/


var quotes = [
  ['War is delightful to those who have had no experience of it.', 'Desiderius Erasmus'],
  ['The sinews of war are not gold, but good soldiers.', 'Niccoló Machiavelli'],
  ['He who wishes to be obeyed must know how to command.', 'Niccoló Machiavelli'],
  ['Strike up the drum and march courageously.', 'Christopher Marlowe'],
  ['Better to reign in hell than serve in heav\'n.', 'John Milton'],
  ['He doth nothing but talk of his horse.', 'Shakespeare, The Merchant of Venice, i, 2'],
  ['All the world\'s a stage, And all the men and women merely players.', 'Shakespeare, As You Like It, ii, 7'],
  ['I will kill thee a hundred and fifty ways.', 'Shakespeare, As You Like It, v, 1'],
  ['Here I and sorrows sit; Here is my throne, bid kings come bow to it.', 'Shakespeare, King John, iii, 1'],
  ['Go, bid the soldiers shoot.', 'Shakespeare, Hamlet, iv, 2'],
  ['A man can die but once.', 'Shakespeare, King Henry IV, Part:II. iii, 2'],
  ['Give me another horse: bind up my wounds.', 'Shakespeare, King Richard III, v, 3'],
  ['A horse! A horse! My kingdom for a horse!', 'Shakespeare, King Richard III, v, 4'],
  ['To whom God will, there be the victory.', 'Shakespeare, King Henry the Sixth, Part:III, ii, 5'],
  ['Inflict not on an enemy every injury in your power, for he may afterwards become your friend.', 'Moslih Eddin Saadi'],
  ['Wars begin when you will, but they do not end when you please.', 'Niccoló Machiavelli'],
  ['He who defends everything defends nothing.', 'Fredrick II, Holy Roman Emperor'],
  ['I am the King of Rome, and above grammar.', 'Sigismund, Holy Roman Emperor'],
  ['When you see contention amongst your enemies, go and sit at ease with your friends; but when you see them of one mind, string your bow, and place stones upon the ramparts.', 'Moslih Eddin Saadi'],
  ['I have loved justice and hated inequity; and therefore I die in exile.', 'Pope Gregory VII, Tuscan Pope'],
  ['It is easy to be brave behind a castle wall.', 'Welsh proverb'],
  ['To carry on war, three things are necessary: money, money, and yet more money.', 'Gian Jacopo Trivulzio'],
  ['Once more unto the breach, dear friends, once more!', 'Shakespeare, King Henry V, iii, 1'],
  ['I speak Spanish to God, Italian to women, French to men, and German to my horse.', 'Charles V, Holy Roman Emperor'],
  ['Had I been present at the creation, I would have given some useful hints for the better ordering of the universe.', 'Alfonso X, the Wise, King of Castile'],
  ['There is now no hope of escaping. If you fight you will conquer, but if you flee you will fall.', 'Fulcher of Chartres'],
  ['O world, thy slippery turns!', 'William Shakespeare, Coriolanus, IV.iv.12'],
  ['Often it does seem such a pity that Noah and his party did not miss the boat.', 'Mark Twain'],
  ['O Liberty! What crimes are committed in thy name!', 'Madame Roland'],
  ['Put your shoulder to the wheel.', 'Aesop'],
  ['Oh farmers, pray that your summers be wet and your winters clear.', 'Virgil'],
  ['Hath not the potter power over the clay, of the same lump to make one vessel unto honour, and another unto dishonour?', 'Romans 9:21'],
  ['Do not throw the arrow which will return against you.', 'Kurdistan proverb'],
  ['It is from their foes, not their friends, that cities learn the lesson of building high walls.', 'Aristophanes'],
  ['If you speak the truth, have a foot in the stirrup.', 'Turkish proverb'],
  ['A god from the machine.', 'Menander'],
  ['For all who draw the sword will die by the sword.', 'Matthew 26:52'],
  ['A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.', 'Antoine de Saint-Exupéry'],
  ['To achieve great things, two things are needed; a plan, and not quite enough time.', 'Lenard Bernstein'],
  ['Man is essentially ignorant, and becomes learned through acquiring knowledge.', 'Ibn Khaldun'],
  ['Art for art\'s sake is an empty phrase. Art for the sake of truth, art for the sake of the good and the beautiful, that is the faith I am searching for.', 'George Sand'],
  ['To administer is to govern: to govern is to reign. That is the essence of the problem.', 'Honore Gabriel Riqueti, comte de Mirabeau'],
  ['Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.', 'Francis Bacon'],
  ['Liberty, not the daughter of order, but the MOTHER of order.', 'Pierre-Joseph Proudhon'],
  ['To name a thing is easy: the difficulty is to discern it before its appearance.', 'Pierre-Joseph Proudhon'],
  ['I have gained this by philosophy: that I do without being commanded what others do only from fear of the law.', 'Aristotle'],
  ['I cannot live without books.', 'Thomas Jefferson'],
  ['The whole is more than the sum of its parts.', 'Aristotle'],
  ['You may delay, but time will not. ', 'Benjamin Franklin'],
  ['They who have put out the people\'s eyes reproach them of their blindness.', 'John Milton'],
  ['Any society that would give up a little liberty to gain a little security will deserve neither and lose both.', 'Benjamin Franklin'],
  ['Like Odysseus, the President looked wiser when he was seated.', 'John Maynard Keynes'],
  ['Compound interest is the most powerful force in the universe.', 'Albert Einstein'],
  ['It has been said that democracy is the worst form of government except all the others that have been tried.', 'Winston Churchill'],
  ['Logic: The art of thinking and reasoning in strict accordance with the limitations and incapacities of the human misunderstanding.', 'Ambroce Bierce'],
  ['History is an account, mostly false, of events, mostly unimportant, which are brought about by rulers, mostly knaves, and soldiers, mostly fools.', 'Ambroce Bierce'],
  ['I must study politics and war that my sons may have liberty to study mathematics and philosophy.', 'John Adams, The 2nd President of United States'],
  ['For once you have tasted flight you will walk the earth with your eyes turned skywards, for there you have been and there you will long to return.', 'Leonardo da Vinci'],
  ['The only thing worse than being talked about is not being talked about.', 'Oscar Wild'],
  ['A good teacher is like a candle – it consumes itself to light the way for others.', 'Arabic proverb'],
  ['Any sufficiently advanced technology is indistinguishable from magic.', 'Arthur C. Clarke'],
  ['Be happy for this moment. This moment is your life.', 'Omar Khayyam'],
  ['When a man appreciates only eating and sleeping, what excellence has he over the reptiles?', 'Saadi Shirazi'],
  ['Those who do not move, do not notice their chains.', 'Rosa Luxenburg'],
  ['Freedom is always the freedom of dissenters.', 'Rosa Luxenburg'],
  ['Liberty cannot be established without morality, nor morality without faith.', 'Alexis de Tocqueville'],
  ['It\'s time for the human race to enter the solar system.', 'Dan Quayle'],
  ['The future will be better tomorrow.', 'Dan Quayle'],
  ['If we don\'t succeed we run the risk of failure.', 'Dan Quayle'],
  ['Just because you do not take an interest in politics...does not mean that politics won\'t take an interest in you.', 'Pericles'],
  ['Quintilius Varus, give me back my legions!', 'Augustus Caesar'],
  ['Hypocrisy is the homage vice pays to virtue.', 'Francois de La Rochefoucauld'],
  ['No man is clever enough to know all the evil he does', 'Francois de La Rochefoucauld'],
  ['We promise according to our hopes and perform according to our fears.', 'Francois de La Rochefoucauld'],
  ['Competitions are for horses, not artists', 'Bela Bartok'],
  ['Lesser artists borrow, great artists steal.', 'Igor Stravinsky'],
  ['Life well spent is long.', 'Giovanni da Palestrina'],
  ['Do there exist many worlds, or is there but a single world? This is one of the most noble and exalted questions in the study of Nature.', 'Albertus Magnus'],
  ['The world is divided into men who have wit and no religion and men who have religion and no wit.', 'Ibn Sina'],
  ['We live for books.', 'Umberto Eco'],
  ['When men stop believing in God, it isn\'t that they then believe in nothing: they believe in everything.', 'Umberto Eco'],
  ['All poets write bad poetry. Bad poets publish them, good poets burn them.', 'Umberto Eco'],
  ['What you plant here, you will reap there.', 'Ibn Arabi'],
  ['Man is the child of customs, not the child of his ancestors.', 'Ibn Khaldun'],
  ['Lottery: A tax on people who are bad at math.', 'Ambrose Bierce'],
  ['A good marriage would be between a blind wife and a deaf husband.', 'Michel de Montaigne'],
  ['Hell is empty and all the Devils are here', 'William Shakespeare, The Tempest, i, 2'],
  ['I must say I find television very educational. The minute somebody turns it on, I go to the library and read a good book.', 'Groucho Marx'],
  ['Society often forgives the criminal; it never forgives the dreamer.', 'Oscar Wild'],
  ['My advice to you is get married: if you find a good wife you’ll be happy; if not, you’ll become a philosopher.', 'Socrates'],
  ['Abandon all hope, you who enter!', 'Dante Alighieri'],
  ['There is no greater pain than to remember a happy time when one is in misery.', 'Dante Alighieri'],
  ['Furthermore, I think Carthage must be destroyed.', 'Cato the Elder'],
  ['I prefer to do right and get no thanks than to do wrong and receive no punishment.', 'Cato the Elder'],
  ['Truth is often eclipsed but never extinguished.', 'Livy'],
  ['Acquaintance lessens fame.', 'Claudius, Roman Emperor'],
  ['Say not always what you know, but always know what you say.', 'Claudius, Roman Emperor'],
  ['Death is less bitter punishment than death\'s delay.', 'Ovid'],
  ['If you wish to be a writer; write!', 'Epictetus'],
  ['There is no wealth like knowledge, no poverty like ignorance.', 'Ali bin Abi Talib'],
  ['A conqueror is always a lover of peace.', 'Carl von Crausewitz'],
  ['The surest way of achieving your goal is through the single-minded pursuit of simple actions.', 'Helmuth von Moltke the Elder'],
  ['Eternal peace is a dream - and not even a beautiful one.', 'Helmuth von Moltke the Elder'],
  ['God gave humans language so they could conceal their thoughts from one another.', 'Charles Maurice de Talleyrand-Perigord'],
  ['There is one person that is wiser than anybody, and that is everybody.', 'Charles Maurice de Talleyrand-Perigords'],
  ['I do not belong to any faction, I will fight them all.', 'Louis Antoine de Saint-just'],
  ['Soldiers, when I give the command to fire, fire straight at my heart. Wait for the order. It will be my last to you. I protest against my condemnation. I have fought a hundred battles for France, and not one against her ... Soldiers, fire!', 'Michel Ney'],
  ['Science never solves a problem without creating ten more.', 'George Bernard Shaw'],
  ['Work is the curse of the drinking classes.', 'Oscar Wilde'],
  ['There is only one thing in life worse than being talked about, and that is not being talked about.', 'Oscar Wilde'],
  ['The old believe everything, the middle-aged suspect everything, the young know everything.', 'Oscar Wilde'],
  ['We cannot tear out a single page of our life, but we can throw the whole book in the fire.', 'George Sand'],
  ['Historians are like deaf people who go on answering questions that no one has asked them.', 'Leo Tolstoy'],
  ['Without him nothing was done, and through him everything was done, and the king trusted him more than any other.', 'Jean Froissart'],
  ['Don\'t forget your great guns, which are the most respectable arguments of the rights of kings.', 'Frederick the Great'],
  ['A crown is merely a hat that lets the rain in.', 'Frederick the Great'],
  ['The souls of emperors and cobblers are cast in the same mold.', 'Michel de Montaigne'],
  ['Once a word has been allowed to escape, it cannot be recalled.', 'Horace'],
  ['O imitators, you slavish herd!', 'Horace'],
  ['Potter is jealous of potter, and craftsman of craftsman; and the poor have a grudge against the poor, and the poet against the poet.', 'Hesiod'],
  ['The art is eternal, their shapes are changing.', 'Rudolf Steiner'],
  ['Beauty is boring because it is predictable.', 'Umberto Eco'],
  ['One can be a great poet and be politically stupid.', 'Umberto Eco'],
  ['Of all the noises known to man, opera is the most expensive.', 'Moriere'],
  ['The more often a stupidity is repeated, the more it gets the appearance of wisdom.', 'Voltaire'],
  ['Don\'t think money does everything or you are going to end up doing everything for money.', 'Voltaire'],
  ['What is history? The lie that everyone agrees on...', 'Voltaire'],
  ['The more I read, the more I acquire, the more certain I am that I know nothing.', 'Voltaire'],
  ['To hold a pen is to be at war.', 'Voltaire'],
  ['The face of tyranny Is always mild at first.', 'Jean Racine'],
  ['All is asleep: the army, the wind, and Neptune.', 'Jean Racine'],
  ['All things are Nothing to Me.', 'Max Stilner'],
  ['The state calls its own violence law, but that of the individual, crime.', 'Max Stilner'],
  ['Each individual is a species unto him/herself.', 'Rudolf Steiner'],
  ['The more I see of men, the better I like my dog.', 'Frederick the Great'],
  ['Diplomacy without military might is like music without instruments.', 'Frederick the Great'],
  ['The manner of giving is worth more than the gift.', 'Pierre Corneille'],
  ['Oh rage! Oh despair! Oh age, my enemy!', 'Pierre Corneille'],
  ['There are now no Pyrenees.', 'Louis XIV, the King of France'],
  ['Clemency is also a revolutionary measure.', 'Camille Desmoulins'],
  ['The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.', 'Bertrand Russell'],
  ['Every great idea starts out as a blasphemy.', 'Bertrand Russell'],
  ['Men are born ignorant, not stupid. They are made stupid by education.', 'Bertrand Russell'],
  ['When you go into court you are putting your fate into the hands of twelve people who weren’t smart enough to get out of jury duty.', 'Noam Chomsky'],
  ['When opportunity knocks, some people are in the backyard looking for four-leaf clovers.', 'Polish proverb'],
  ['I never forget a face—but in your case, I’ll be glad to make an exception.', 'Groucho Marx'],
  ['The farther backward you can look, the farther forward you are likely to see.', 'Winston Churchill'],
  ['The inherent vice of capitalism is the unequal sharing of blessings. The inherent virtue of socialism is the equal sharing of miseries.', 'Winston Churchill'],
  ['The short words are the best, and the old words best of all.', 'Winston Churchill'],
  ['Even wisdom has to yield to self-interest.', 'Pindar'],
  ['If history is deprived of the Truth, we are left with nothing but an idle, unprofitable tale.', 'Polybius'],
  ['The luck of having talent is not enough; one must also have a talent for luck.', 'Hector Berlioz'],
  ['Richard Wagner, a musician who wrote music which is better than it sounds.', 'Richard Wagner'],
  ['Life gives nothing to man without labor.', 'Horace'],
  ['Knowledge without education is but armed injustice', 'Horace'],
  ['The world is divided into men who have wit and no religion and men who have religion and no wit.', 'Ibn Rushd'],
  ['Teach thy tongue to say \'I do not know\', and thou shalt progress.', 'Maimonides'],
  ['I will destroy my enemies by converting them to friends.', 'Maimonides'],
  ['The goal of good health is to enable a person to acquire wisdom.', 'Maimonides'],
  ['If there is a God, whence proceed so many evils? If there is no God, whence cometh any good?', 'Boethius'],
  ['With man, most of his misfortunes are occasioned by man.', 'Pliny the Elder'],
  ['When a building is about to fall down, all the mice desert it.', 'Pliny the Elder'],
  ['Many dishes bring many diseases.', 'Pliny the Elder'],
  ['A mind needs books as a sword needs a whetstone, if it is to keep its edge.', 'George R.R. Martin'],
  ['A reader lives a thousand lives before he dies.', 'George R.R. Martin']
  ['People often claim to hunger for truth, but seldom like the taste when it\'s served up.', 'George R.R. Martin, "A Song of Ice and Fire"'],
  ['He who destroys a good book kills reason itself.', 'John Milton'],
  ['Give me the liberty to know, to utter, and to argue freely according to conscience, above all liberties.', 'John Milton'],
  ['Art is a hammer to beat the world, not a mirror to reflect it.', 'Nikolai Nekrasov'],
  ['Certainly in each social period, youth must be made to venerate the dominant absurdities.', 'Charles Fourier'],
  ['Softness to traitors will destroy us all.', 'Maximilien Robespierre'],
  ['When a Banker jumps out of a window, jump after him - that\'s where the money is.', 'Maximilien Robespierre'],
  ['In everything, there is a share of everything.', 'Anaxagoras'],
  ['The sun provides the moon with its brightness.', 'Anaxagoras'],
  ['Nothing is more useful than silence.', 'Menander'],
  ['There are many wild beasts on land and in the sea, but the beastliest of all is woman.', 'Menander'],
  ['Whom the gods love dies young.', 'Whom the gods love dies young.', 'Menander'],
  ['The workman still is greater than his work.', 'Medander'],
  ['A man that runs away may fight again.', 'Medander'],
  ['Quickly, bring me a beaker of wine, so that I may wet my mind and say something clever.', 'Aristophanes'],
  ['Ignorance can be cured, but stupidity is forever.', 'Aristophanes'],
  ['By words the mind is winged.', 'Aristophanes'],
  ['Comedy is allied to justice.', 'Aristophanes'],
  ['The tyrant is a child of pride.', 'Sophocles'],
  ['What you cannot enforce, do not command.', 'Sophocles'],
  ['It will not always be summer: build barns.', 'Hesiod'],
  ['Memory is the mother of all wisdom.', 'Aeschylus'],
  ['It is change; all yields its place and goes.', 'Euripides'],
  ['You will stir up the hornets.', 'Plautus'],
  ['There is no book so bad that it is not profitable in some part.', 'Pliny the Younger'],
  ['The physician can bury his mistakes, but the architect can only advise his client to plant vines.', 'Frank Lloyd Wright'],
  ['Thou shalt not muzzle the ox when he treadeth out the corn.', 'Deuteronomy 25:4'],
  ['Those who cannot remember the past are condemned to repeat it.', 'George Santayana'],
  ['Computers are like Old Testament gods: lots of rules and no mercy.', 'Joseph Campbell'],
  ['No man ever wetted clay and then left it, as if there would be bricks by chance and fortune.', 'Plutarch'],
  ['I don\'t believe in astrology; I\'m a Sagittarius and we\'re skeptical.', 'Arthur C. Clarke'],
  ['Bronze is the mirror of the form, wine of the mind.', 'Aeschylus'],
  ['You and I come by road or rail, but economists travel on infrastructure.', 'Margaret Thatcher'],
  ['The single biggest problem in communication is the illusion that it has taken place.', 'George Bernard Shaw'],
  ['Woe to me, my mother, that you have borne me As a man of strife and a man of contention to all the land! I have not lent, nor have men lent money to me, Yet everyone curses me.', 'Jeremiah 15:10'],
  ['War does not determine who is right - only who is left.', 'Bertrand Russell'],
  ['People never lie so much as after a hunt, during a war or before an election.', 'Otto von Bismarck'],
  ['Woe to the defeated!', 'Brennus'],
  ['Oh, Durendal, how beautiful you are, how clear, how bright! How you shine and flash against the sun!', 'from "the Song of Roland"'],
  ['I will not wear a crown of gold where my Savior wore one of thorns', 'Godfrey of Bouillon'],
  ['Death twitches my ear. Live, he says, I am coming.', 'Virgil'],
  ['Fortune sides with him who dares.', 'Virgil'],
  ['Any old woman can love God better than a doctor of theology can.', 'Bonaventure'],
  ['The three most important virtues are humility, humility, and humility.', 'Bernard of Clairvaux'],
  ['Give light, and the darkness will disappear of itself.', 'Desiderius Erasmus'],
  ['The main hope of a nation lies in the proper education of its youth', 'Desiderius Erasmus'],
  ['Your library is your paradise.', 'Desiderius Erasmus'],
  ['The cat would eat fish but would not get her feet wet.', 'Geoffrey Chaucer'],
  ['Antichrist is Mammon\'s son.', 'John Milton'],
  ['Biochemically, love is just like eating large amounts of chocolate.', 'John Milton'],
  ['Falsehood flies, and the truth comes limping after it.', 'Jonathan Swift'],
  ['Every man desires to live long, but no man wishes to be old.','Jonathan Swift'],
  ['Promises and pie-crust are made to be broken.', 'Jonathan Swift'],
  ['It is the talent of human nature to run from one extreme to another.', 'Jonathan Swift'],
  ['If you want good laws, burn those you have and make new ones.', 'Voltaire'],
  ['Governments need to have both shepherds and butchers.', 'Voltaire'],
  ['It is dangerous to be right when the government is wrong.', 'Voltaire'],
  ['Originality is nothing but judicious plagiarism.', 'Voltaire'],
  ['There are no sects in geometry.', 'Voltaire'],
  ['What is history? The lie that everyone agrees on...', 'Voltaire'],
  ['Democracy is just a filler for textbooks! Do you actually believe that public opinion influences the government?', 'Voltaire'],
  ['Language is a very difficult thing to put into words.', 'Voltaire'],
  ['There is another world, but it is in this one.', 'William Butler Yeats'],
  ['Twelve highlanders and a bagpipe make a rebellion.', 'Scotish Proverb'],
  ['Fools look to tomorrow; wise men use tonight.', 'Scotish Proverb'],
  ['Never marry for money. You can borrow it cheaper.', 'Scotish Proverb'],
  ['Width of life is more important than length of life.', 'Ibn Sina'],
  ['The person who predicts the future is lying, even when he is right.', 'Arabic Proverb'],
  ['Keep away from trouble and sing to it.', 'Syrian Proverb'],
  ['Curiosity is the first step to hell.', 'Polish Proverb'],
  ['Where devil cannot go, he will send a woman.', 'Polish Proverb'],
  ['It is easiest to learn from another man\'s damage.', 'Venetian Proverb'],
  ['Crooked logs make straight fires.', 'Italian Proverb']
]

document.addEventListener("DOMContentLoaded", function(event) {

  var availableCollection = JSON.parse(localStorage.getItem('quotes'));
  var remainingQuantity = availableCollection ? availableCollection.length : 0

  if (remainingQuantity > 0 || remainingQuantity != quotes.length) {
    availableCollection = quotes
  }

  var index = Math.floor(Math.random()*remainingQuantity)
  var quote = availableCollection[index];

  document.getElementById('quote-line').innerHTML = quote[0];
  document.getElementById('quote-author').innerHTML = quote[1];
  availableCollection.splice(index, 1);

  localStorage.setItem('quotes', JSON.stringify(availableCollection));
});
